import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { WorkspaceShell } from "@/components/shell/WorkspaceShell";
import { Card } from "@/components/ui/Card";
import { Badge } from "@/components/ui/Badge";
import { Link, redirect } from "@/i18n/navigation";
import { supabaseEnv } from "@/lib/supabase/config";
import { getUser } from "@/lib/supabase/server";
import { getCurrentRole } from "@/lib/data/org";
import { getArtifact } from "@/lib/data/artifacts";
import { listReviewers } from "@/lib/data/reviewers";
import { PromotionForm } from "@/components/review/PromotionForm";
import { approveArtifact } from "../actions";

export default async function ArtifactPage({
  params,
}: {
  params: Promise<{ locale: string; id: string }>;
}) {
  const { locale, id } = await params;
  setRequestLocale(locale);

  // Artifacts only exist when Supabase is configured.
  if (!supabaseEnv.isConfigured) redirect({ href: "/evidence", locale });
  if (!(await getUser())) redirect({ href: "/login", locale });

  const artifact = await getArtifact(id);
  if (!artifact) notFound();

  const t = await getTranslations("evidence");
  const tArtifacts = await getTranslations("artifacts");
  const tPromote = await getTranslations("promote");

  const role = await getCurrentRole();
  const canApprove =
    (role === "practitioner" || role === "admin") &&
    artifact.review_status === "draft";
  const reviewers = canApprove ? await listReviewers() : [];

  return (
    <WorkspaceShell>
      <Link
        href="/evidence"
        className="mb-4 inline-block text-sm text-indigo hover:underline"
      >
        ← {t("back")}
      </Link>

      <div className="mb-3 flex flex-wrap items-center gap-2">
        <Badge tone={artifact.review_status === "approved" ? "low" : "review"} dot>
          {artifact.review_status === "approved"
            ? t("approvedTag")
            : t("draftTag")}
        </Badge>
        <span className="font-mono text-xs uppercase tracking-wide text-muted">
          {artifact.language} · {t("versionTag", { n: artifact.version })}
        </span>
      </div>

      <h1 className="font-display text-2xl font-bold text-ink">
        {tArtifacts(artifact.type)}
      </h1>

      <p className="mt-2 rounded-tile bg-review-bg px-4 py-3 text-sm text-review">
        {t("aiNotice")}
      </p>

      {artifact.review_status === "approved" ? (
        <p className="mt-3 rounded-tile bg-low-bg px-4 py-3 text-sm text-low">
          {tPromote("approvedNote")}
        </p>
      ) : (
        canApprove && (
          <div className="mt-3">
            <PromotionForm
              action={approveArtifact}
              targetId={artifact.id}
              reviewers={reviewers}
              submitLabel={tPromote("approveArtifact")}
            />
          </div>
        )
      )}

      <Card className="mt-6">
        {/* Content is a clean HTML fragment generated by our own server-side
            Claude call from structured engagement data. */}
        <article
          className="artifact-prose"
          dangerouslySetInnerHTML={{ __html: artifact.content }}
        />
      </Card>
    </WorkspaceShell>
  );
}
